import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const isDemo = location.pathname === '/demo';
const db = createClient('https://jipiurqxddchjtwlmltf.supabase.co', 'sb_publishable_FW1xMNmOPK2EvX6N-fZZSw_DRUUJDUr');
const money = value => new Intl.NumberFormat('en-SG', { style: 'currency', currency: 'SGD' }).format(value || 0);
const dateKey = d => d.toISOString().slice(0, 10);
const categories = { Food:'🍔', Transport:'🚌', Shopping:'🛒', Home:'🏠', Entertainment:'🎬', Health:'💊', Salary:'💼', Freelance:'💻', Capital:'📈', Other:'✦' };
const expenseCategories = ['Food','Transport','Shopping','Home','Entertainment','Health','Other'];
const incomeCategories = ['Salary','Freelance','Capital','Other'];
const demoSeed = () => { const now = new Date(); const ago = days => dateKey(new Date(now.getFullYear(), now.getMonth(), now.getDate()-days)); return [
  { id:'d1', description:'Salary', note:'Monthly salary', category:'Salary', amount:4200, type:'income', transaction_date:ago(9) },
  { id:'d2', description:'Morning groceries', note:'Weekly household shopping', category:'Food', amount:46.8, type:'expense', transaction_date:ago(5) },
  { id:'d3', description:'MRT top-up', note:'', category:'Transport', amount:30, type:'expense', transaction_date:ago(3) },
  { id:'d4', description:"Stuff'd", note:'Lunch with colleagues', category:'Food', amount:11.2, type:'expense', transaction_date:ago(1) },
  { id:'d5', description:'Singtel', note:'Mobile bill', category:'Home', amount:25, type:'expense', transaction_date:ago(0) }
] };
function useStore() {
  const [user, setUser] = useState(isDemo ? { email:'demo@everycentcounts.app', user_metadata:{ username:'Demo user' }} : null);
  const [entries, setEntries] = useState([]); const [budget, setBudget] = useState(0); const [loading, setLoading] = useState(!isDemo);
  const load = async () => {
    if (isDemo) { const saved = JSON.parse(localStorage.getItem('ecc-react-demo') || 'null') || { entries:demoSeed(), budget:1800 }; setEntries(saved.entries); setBudget(saved.budget); setLoading(false); return; }
    const { data:{ session } } = await db.auth.getSession(); if (!session) { setLoading(false); return; } setUser(session.user);
    const [t,b] = await Promise.all([db.from('transactions').select('*').order('transaction_date',{ascending:false}), db.from('budgets').select('monthly_amount').maybeSingle()]);
    setEntries(t.data || []); setBudget(Number(b.data?.monthly_amount || 0)); setLoading(false);
  };
  useEffect(() => { load(); }, []);
  const persist = async (next, nextBudget=budget) => { if (isDemo) { localStorage.setItem('ecc-react-demo', JSON.stringify({entries:next,budget:nextBudget})); setEntries(next); setBudget(nextBudget); return; } await load(); };
  return { user, setUser, entries, budget, setBudget, loading, load, persist };
}
function App() {
  const store = useStore(); const [modal, setModal] = useState(null); const [editing, setEditing] = useState(null); const [month, setMonth] = useState(new Date()); const [weekOffset, setWeekOffset] = useState(0); const [bulk, setBulk] = useState(false); const [selected, setSelected] = useState(new Set()); const yearly = /^\/Yearly|^\/yearly/.test(location.pathname);
  if (store.loading) return <main className="loading">Loading your tracker…</main>;
  if (!store.user) return <Auth onDone={store.load} />;
  const monthPrefix = `${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;
  const monthly = store.entries.filter(x => x.transaction_date.startsWith(monthPrefix));
  const income = monthly.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0);
  const spend = monthly.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0);
  const balance = store.entries.reduce((s,x)=>s+(x.type==='income'?Number(x.amount):-Number(x.amount)),0);
  const name = store.user.user_metadata?.username || store.user.email.split('@')[0];
  const saveTransaction = async values => {
    if (editing) { const { recurrence, end, id, created_at, recurrence_group_id, recurrence_index, recurrence_count, ...row } = values; const updated = { ...row, amount:Number(values.amount), note:values.note||null }; if (isDemo) await store.persist(store.entries.map(entry => entry.id === editing.id ? { ...entry, ...updated } : entry)); else { const { error } = await db.from('transactions').update(updated).eq('id', editing.id); if (error) return alert(error.message); await store.load(); } setModal(null); setEditing(null); return; }
    const dates = repeatDates(values); const rows = dates.map((transaction_date, index)=>({ ...values, id:crypto.randomUUID(), transaction_date, amount:Number(values.amount), note:values.note||null, recurrence_group_id:dates.length>1?crypto.randomUUID():null, recurrence_index:dates.length>1?index+1:null, recurrence_count:dates.length>1?dates.length:null }));
    if (isDemo) await store.persist([...store.entries, ...rows]); else { const { error } = await db.from('transactions').insert(rows.map(({id,...row})=>row)); if (error) return alert(error.message); await store.load(); } setModal(null);
  };
  const remove = async ids => { const list = Array.isArray(ids) ? ids : [ids]; if (!confirm(`Delete ${list.length} selected transaction${list.length===1?'':'s'}?`)) return; if (isDemo) await store.persist(store.entries.filter(x=>!list.includes(x.id))); else { await db.from('transactions').delete().in('id',list); await store.load(); } setSelected(new Set()); };
  const saveBudget = async value => { const numeric=Number(value); if(isDemo) await store.persist(store.entries,numeric); else { await db.from('budgets').upsert({user_id:store.user.id,monthly_amount:numeric},{onConflict:'user_id'}); await store.load(); } setModal(null); };
  return <div className="app-shell"><aside><a className="brand" href="/home"><b>$</b> Every Cent Counts</a><nav><a className="active" href="/home">▦ Monthly</a><a href="/Yearly">◫ Yearly</a></nav><div className="account">{isDemo && <a className="actual" href="/home">↗ Use the actual app here</a>}<div className="avatar">{name[0].toUpperCase()}</div><div><strong>{name}</strong><small>{store.user.email}</small></div>{!isDemo && <button onClick={async()=>{await db.auth.signOut();location.reload()}}>Sign out</button>}</div></aside>
    <main><header>{yearly?<div className="month yearly-header"><a href="/home">‹</a><strong>{new Date().getFullYear()}</strong><a href="/home">›</a></div>:<div className="month"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><input type="month" value={monthPrefix} onChange={e=>{const [y,m]=e.target.value.split('-');setMonth(new Date(y,m-1,1))}}/><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div>}</header><section className="content">{yearly ? <Yearly entries={store.entries}/> : <><div className="hero"><div><p>{month.toLocaleDateString('en-SG',{month:'long',year:'numeric'}).toUpperCase()} AT A GLANCE</p><h1>Money, with a little <em>more clarity.</em></h1></div><button className="primary" onClick={()=>{setEditing(null);setModal('transaction')}}>＋ Add transaction</button></div><section className="metrics"><Metric label="Available balance" value={money(balance)} dark/><Metric label="Income" value={money(income)} /><Metric label="Spending" value={money(spend)} /><Metric label="Saving rate" value={`${income?Math.max(0,Math.round((income-spend)/income*100)):0}%`} /></section>
      <section className="grid"><Panel title="Monthly spending" action="Edit budget" onAction={()=>setModal('budget')}><Budget used={spend} budget={store.budget} entries={monthly}/></Panel><Panel title="Daily activity"><Bars entries={monthly} offset={weekOffset} onPrevious={()=>setWeekOffset(x=>x-1)} onNext={()=>setWeekOffset(x=>x+1)}/></Panel></section>
      <Panel title="Recent transactions" action={bulk?'Done':'Edit'} onAction={()=>{setBulk(!bulk);setSelected(new Set())}}>{bulk&&<div className="bulkbar"><span>{selected.size} selected</span><button disabled={!selected.size} onClick={()=>remove([...selected])}>Delete selected</button></div>}<Transactions entries={monthly} bulk={bulk} selected={selected} onToggle={id=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})} onEdit={entry=>{setEditing(entry);setModal('transaction')}}/></Panel></>}
    </section></main>
    {modal==='transaction'&&<TransactionModal entry={editing} suggestions={[...new Set(store.entries.map(x=>x.description))]} onClose={()=>setModal(null)} onSave={saveTransaction}/>} {modal==='budget'&&<BudgetModal budget={store.budget} onClose={()=>setModal(null)} onSave={saveBudget}/>}</div>;
}
const Metric=({label,value,dark,entries=[],arrow})=><article className={`metric ${dark?'dark':''} detail-tip`} data-tip={entries.length?entries.map(x=>`${x.description} · ${money(x.amount)}`).join('\n'):'No transactions'}><small>{label}{arrow&&<i className="metric-arrow">{arrow}</i>}</small><strong>{value}</strong><span>This month</span></article>;
const Panel=({title,action,onAction,children})=><section className="panel"><div className="panel-head"><h2>{title}</h2>{action&&<button onClick={onAction}>{action}</button>}</div>{children}</section>;
function Budget({used,budget,entries}) { const groups=expenseCategories.map(category=>{const rows=entries.filter(x=>x.type==='expense'&&x.category===category);return [category,rows.reduce((s,x)=>s+Number(x.amount),0),rows]}).filter(x=>x[1]); return <><div className="budget"><div className="ring"><b>{budget?Math.round(used/budget*100):0}%</b><small>used</small></div><div><strong>{money(Math.max(0,budget-used))} left to spend</strong><p>{money(used)} of {money(budget)} monthly budget</p></div></div><div>{groups.map(([cat,total,rows])=><div className="category detail-tip" data-tip={rows.map(x=>`${x.description} · ${money(x.amount)}`).join('\n')} key={cat}><span>{categories[cat]} {cat}</span><b>{money(total)}</b></div>)}</div></> }
function Bars({entries,offset,onPrevious,onNext}) { const anchor=new Date();anchor.setDate(anchor.getDate()-anchor.getDay()+1+offset*7); const days=Array.from({length:7},(_,i)=>{const d=new Date(anchor);d.setDate(anchor.getDate()+i);return d}); const items=days.map(d=>entries.filter(x=>x.type==='expense'&&x.transaction_date===dateKey(d))); const amounts=items.map(rows=>rows.reduce((s,x)=>s+Number(x.amount),0)); const max=Math.max(...amounts,1); const avg=amounts.reduce((s,x)=>s+x,0)/7; return <><div className="week-nav"><button onClick={onPrevious}>←</button><span>{days[0].toLocaleDateString('en-SG',{day:'numeric',month:'short'})} – {days[6].toLocaleDateString('en-SG',{day:'numeric',month:'short'})}</span><button onClick={onNext}>→</button></div><div className="activity-summary"><strong>{money(amounts.reduce((s,x)=>s+x,0))}</strong><span>total · average {money(avg)} daily</span></div><div className="bars">{amounts.map((value,i)=><div key={i}><span className="detail-tip" data-tip={items[i].length?items[i].map(x=>`${x.description} · ${money(x.amount)}`).join('\n'):'No transactions'} style={{height:`${Math.max(4,value/max*100)}px`}}></span><small>{days[i].toLocaleDateString('en-SG',{weekday:'narrow'})}</small></div>)}</div><p className="insight">✦ You have kept your spending activity visible — a steady start.</p></> }
function Transactions({entries,bulk,selected,onToggle,onEdit}) { const [page,setPage]=useState(1); const ordered=[...entries].sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date)); const pages=Math.max(1,Math.ceil(ordered.length/6)); const shown=ordered.slice((page-1)*6,page*6); useEffect(()=>setPage(value=>Math.min(value,pages)),[pages]); return <><div className="ledger">{shown.map(x=><div className={`row ${bulk?'bulk-row':''}`} key={x.id}>{bulk&&<input type="checkbox" checked={selected.has(x.id)} onChange={()=>onToggle(x.id)} aria-label={`Select ${x.description}`}/>}<span className="icon">{categories[x.category]||'✦'}</span><div><strong>{x.description}</strong><small>{x.note||x.category}</small></div><time>{new Date(`${x.transaction_date}T00:00:00`).toLocaleDateString('en-SG',{day:'numeric',month:'short'})}</time><b className={x.type}>{x.type==='income'?'+':'−'}{money(x.amount)}</b><button onClick={()=>onEdit(x)} aria-label={`Edit ${x.description}`}>✎</button></div>)}</div>{pages>1&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next →</button></div>}</> }
function Yearly({entries}) { const year=new Date().getFullYear(); const months=Array.from({length:12},(_,index)=>new Date(year,index,1)); const inYear=entries.filter(x=>x.transaction_date.startsWith(String(year))); const total=(type)=>money(inYear.filter(x=>x.type===type).reduce((s,x)=>s+Number(x.amount),0)); return <><div className="yearly-intro"><div><p>YEARLY OVERVIEW</p><h1>Your year, in<br/><em>one clear view.</em></h1></div><span>Every month’s income, spending and progress in one place.</span></div><section className="metrics yearly-metrics"><Metric label="Yearly income" value={total('income')} dark/><Metric label="Yearly spending" value={total('expense')}/><Metric label="Net change" value={money(inYear.reduce((s,x)=>s+(x.type==='income'?1:-1)*Number(x.amount),0))}/></section><Panel title={`${year} financial summary`}><div className="yearly-table"><div className="yearly-head"><span>MONTH</span><span>INCOME</span><span>SPENDING</span><span>NET CHANGE</span></div>{months.map(month=>{const prefix=`${year}-${String(month.getMonth()+1).padStart(2,'0')}`;const rows=entries.filter(x=>x.transaction_date.startsWith(prefix));const inc=rows.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0);const spend=rows.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0);return <div className="yearly-row" key={prefix}><strong>{month.toLocaleDateString('en-SG',{month:'long'})}</strong><span>{money(inc)}</span><span>{money(spend)}</span><b>{money(inc-spend)}</b></div>})}</div></Panel></>}
function TransactionModal({entry,suggestions=[],onClose,onSave}) { const [form,setForm]=useState(entry||{type:'expense',description:'',note:'',amount:'',category:'Food',transaction_date:dateKey(new Date()),recurrence:'once',end:''}); const choices=form.type==='income'?incomeCategories:expenseCategories; useEffect(()=>{if(!choices.includes(form.category))setForm(x=>({...x,category:choices[0]}))},[form.type]); const submit=e=>{e.preventDefault();onSave({...form});}; return <Modal title={entry?'Edit transaction':'Add transaction'} onClose={onClose}><form onSubmit={submit}><div className="toggle">{['expense','income'].map(type=><button type="button" className={form.type===type?'selected':''} onClick={()=>setForm({...form,type})} key={type}>{type}</button>)}</div><label>Description<input required list="description-history" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><datalist id="description-history">{suggestions.map(x=><option key={x} value={x}/>)}</datalist></label><label>Note<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="two"><label>Amount<input required type="number" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{choices.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Date<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><label>Repeat<select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}><option value="once">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="biweekly">Bi-weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label>{form.recurrence!=='once'&&<label>Ends on<input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label>}<button className="primary" type="submit">Save transaction</button></form></Modal> }
function BudgetModal({budget,onClose,onSave}) { const [value,setValue]=useState(budget);return <Modal title="Set monthly budget" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(value)}}><label>Monthly spending budget<input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)}/></label><button className="primary">Save budget</button></form></Modal> }
const Modal=({title,onClose,children})=><div className="backdrop"><section className="modal"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>;
function Auth({onDone}) { const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [signup,setSignup]=useState(false);const [message,setMessage]=useState('');const submit=async e=>{e.preventDefault();const r=signup?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error)setMessage(r.error.message);else if(signup)setMessage('Account created. Check your email, then sign in.');else onDone()};return <main className="auth"><form onSubmit={submit}><b className="logo">$</b><h1>{signup?'Create your account':'Sign in'}</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="8"/></label><p>{message}</p><button className="primary">{signup?'Create account':'Sign in'}</button><button type="button" className="link" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'Need an account? Sign up'}</button></form></main> }
function repeatDates(form) { if(form.recurrence==='once'||!form.end)return [form.transaction_date];const start=new Date(`${form.transaction_date}T00:00:00`),end=new Date(`${form.end}T00:00:00`),out=[];for(let i=0;i<500;i++){let d=new Date(start);if(form.recurrence==='daily')d.setDate(d.getDate()+i);else if(form.recurrence==='weekly')d.setDate(d.getDate()+i*7);else if(form.recurrence==='biweekly')d.setDate(d.getDate()+i*14);else d.setMonth(d.getMonth()+i*(form.recurrence==='quarterly'?3:form.recurrence==='yearly'?12:1));if(d>end)break;out.push(dateKey(d))}return out;}
createRoot(document.getElementById('root')).render(<App/>);
