import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const isDemo = location.pathname === '/demo';
const db = createClient('https://jipiurqxddchjtwlmltf.supabase.co', 'sb_publishable_FW1xMNmOPK2EvX6N-fZZSw_DRUUJDUr');
const money = value => new Intl.NumberFormat('en-SG', { style: 'currency', currency: 'SGD' }).format(value || 0);
const dateKey = d => d.toISOString().slice(0, 10);
const categories = { Food:'🍔', Transport:'🚌', Shopping:'🛒', Home:'🏠', Entertainment:'🎬', Health:'💊', Salary:'💼', Freelance:'💻', Capital:'📈', Other:'✦' };
const expenseCategories = ['Food','Transport','Shopping','Home','Entertainment','Health','Other'];
const incomeCategories = ['Salary','Freelance','Capital','Other'];
const demoSeed = () => { const now = new Date(); const ago = days => dateKey(new Date(now.getFullYear(), now.getMonth(), now.getDate()-days)); return [
  { id:'d1', description:'Salary', note:'Monthly salary', category:'Salary', amount:4200, type:'income', transaction_date:ago(9) },
  { id:'d2', description:'Morning groceries', note:'Weekly household shopping', category:'Food', amount:46.8, type:'expense', transaction_date:ago(5) },
  { id:'d3', description:'MRT top-up', note:'', category:'Transport', amount:30, type:'expense', transaction_date:ago(3) },
  { id:'d4', description:"Stuff'd", note:'Lunch with colleagues', category:'Food', amount:11.2, type:'expense', transaction_date:ago(1) },
  { id:'d5', description:'Singtel', note:'Mobile bill', category:'Home', amount:25, type:'expense', transaction_date:ago(0) }
] };
function useStore() {
  const [user, setUser] = useState(isDemo ? { email:'demo@everycentcounts.app', user_metadata:{ username:'Demo user' }} : null);
  const [entries, setEntries] = useState([]); const [budget, setBudget] = useState(0); const [loading, setLoading] = useState(!isDemo);
  const load = async () => {
    if (isDemo) { const saved = JSON.parse(localStorage.getItem('ecc-react-demo') || 'null') || { entries:demoSeed(), budget:1800 }; setEntries(saved.entries); setBudget(saved.budget); setLoading(false); return; }
    const { data:{ session } } = await db.auth.getSession(); if (!session) { setLoading(false); return; } setUser(session.user);
    const [t,b] = await Promise.all([db.from('transactions').select('*').order('transaction_date',{ascending:false}), db.from('budgets').select('monthly_amount').maybeSingle()]);
    setEntries(t.data || []); setBudget(Number(b.data?.monthly_amount || 0)); setLoading(false);
  };
  useEffect(() => { load(); }, []);
  const persist = async (next, nextBudget=budget) => { if (isDemo) { localStorage.setItem('ecc-react-demo', JSON.stringify({entries:next,budget:nextBudget})); setEntries(next); setBudget(nextBudget); return; } await load(); };
  return { user, setUser, entries, budget, setBudget, loading, load, persist };
}
function App() {
  const store = useStore(); const [modal, setModal] = useState(null); const [editing, setEditing] = useState(null); const [month, setMonth] = useState(new Date());
  if (store.loading) return <main className="loading">Loading your tracker…</main>;
  if (!store.user) return <Auth onDone={store.load} />;
  const monthPrefix = `${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;
  const monthly = store.entries.filter(x => x.transaction_date.startsWith(monthPrefix));
  const income = monthly.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0);
  const spend = monthly.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0);
  const balance = store.entries.reduce((s,x)=>s+(x.type==='income'?Number(x.amount):-Number(x.amount)),0);
  const name = store.user.user_metadata?.username || store.user.email.split('@')[0];
  const add = async values => {
    const dates = repeatDates(values); const rows = dates.map((transaction_date, index)=>({ ...values, id:crypto.randomUUID(), transaction_date, amount:Number(values.amount), note:values.note||null, recurrence_group_id:dates.length>1?crypto.randomUUID():null, recurrence_index:dates.length>1?index+1:null, recurrence_count:dates.length>1?dates.length:null }));
    if (isDemo) await store.persist([...store.entries, ...rows]); else { const { error } = await db.from('transactions').insert(rows.map(({id,...row})=>row)); if (error) return alert(error.message); await store.load(); } setModal(null);
  };
  const remove = async id => { if (!confirm('Delete this transaction?')) return; if (isDemo) await store.persist(store.entries.filter(x=>x.id!==id)); else { await db.from('transactions').delete().eq('id',id); await store.load(); } };
  const saveBudget = async value => { const numeric=Number(value); if(isDemo) await store.persist(store.entries,numeric); else { await db.from('budgets').upsert({user_id:store.user.id,monthly_amount:numeric},{onConflict:'user_id'}); await store.load(); } setModal(null); };
  return <div className="app-shell"><aside><a className="brand" href="/home"><b>$</b> Every Cent Counts</a><nav><a className="active" href="/home">▦ Monthly</a><a href="/Yearly">◫ Yearly</a></nav><div className="account">{isDemo && <a className="actual" href="/home">↗ Use the actual app here</a>}<div className="avatar">{name[0].toUpperCase()}</div><div><strong>{name}</strong><small>{store.user.email}</small></div>{!isDemo && <button onClick={async()=>{await db.auth.signOut();location.reload()}}>Sign out</button>}</div></aside>
    <main><header><div className="month"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><input type="month" value={monthPrefix} onChange={e=>{const [y,m]=e.target.value.split('-');setMonth(new Date(y,m-1,1))}}/><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></header><section className="content"><div className="hero"><div><p>{month.toLocaleDateString('en-SG',{month:'long',year:'numeric'}).toUpperCase()} AT A GLANCE</p><h1>Money, with a little <em>more clarity.</em></h1></div><button className="primary" onClick={()=>{setEditing(null);setModal('transaction')}}>＋ Add transaction</button></div>
      <section className="metrics"><Metric label="Available balance" value={money(balance)} dark/><Metric label="Income" value={money(income)} /><Metric label="Spending" value={money(spend)} /><Metric label="Saving rate" value={`${income?Math.max(0,Math.round((income-spend)/income*100)):0}%`} /></section>
      <section className="grid"><Panel title="Monthly spending" action="Edit budget" onAction={()=>setModal('budget')}><Budget used={spend} budget={store.budget} entries={monthly}/></Panel><Panel title="Daily activity"><Bars entries={monthly}/></Panel></section>
      <Panel title="Recent transactions" action="Add transaction" onAction={()=>setModal('transaction')}><Transactions entries={monthly} onDelete={remove} onEdit={entry=>{setEditing(entry);setModal('transaction')}}/></Panel>
    </section></main>
    {modal==='transaction'&&<TransactionModal entry={editing} onClose={()=>setModal(null)} onSave={add}/>} {modal==='budget'&&<BudgetModal budget={store.budget} onClose={()=>setModal(null)} onSave={saveBudget}/>}</div>;
}
const Metric=({label,value,dark})=><article className={`metric ${dark?'dark':''}`}><small>{label}</small><strong>{value}</strong><span>This month</span></article>;
const Panel=({title,action,onAction,children})=><section className="panel"><div className="panel-head"><h2>{title}</h2>{action&&<button onClick={onAction}>{action}</button>}</div>{children}</section>;
function Budget({used,budget,entries}) { const groups=expenseCategories.map(category=>[category,entries.filter(x=>x.type==='expense'&&x.category===category).reduce((s,x)=>s+Number(x.amount),0)]).filter(x=>x[1]); return <><div className="budget"><div className="ring"><b>{budget?Math.round(used/budget*100):0}%</b><small>used</small></div><div><strong>{money(Math.max(0,budget-used))} left to spend</strong><p>{money(used)} of {money(budget)} monthly budget</p></div></div><div>{groups.map(([cat,total])=><div className="category" key={cat}><span>{categories[cat]} {cat}</span><b>{money(total)}</b></div>)}</div></> }
function Bars({entries}) { const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d}); const amounts=days.map(d=>entries.filter(x=>x.type==='expense'&&x.transaction_date===dateKey(d)).reduce((s,x)=>s+Number(x.amount),0)); const max=Math.max(...amounts,1); return <div className="bars">{amounts.map((value,i)=><div key={i}><span title={money(value)} style={{height:`${Math.max(4,value/max*130)}px`}}></span><small>{days[i].toLocaleDateString('en-SG',{weekday:'narrow'})}</small></div>)}</div> }
function Transactions({entries,onDelete,onEdit}) { return <div className="ledger">{[...entries].sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date)).slice(0,10).map(x=><div className="row" key={x.id}><span className="icon">{categories[x.category]||'✦'}</span><div><strong>{x.description}</strong><small>{x.note||x.category}</small></div><time>{new Date(`${x.transaction_date}T00:00:00`).toLocaleDateString('en-SG',{day:'numeric',month:'short'})}</time><b className={x.type}>{x.type==='income'?'+':'−'}{money(x.amount)}</b><button onClick={()=>onEdit(x)}>✎</button><button onClick={()=>onDelete(x)}>×</button></div>)}</div> }
function TransactionModal({entry,onClose,onSave}) { const [form,setForm]=useState(entry||{type:'expense',description:'',note:'',amount:'',category:'Food',transaction_date:dateKey(new Date()),recurrence:'once',end:''}); const choices=form.type==='income'?incomeCategories:expenseCategories; useEffect(()=>{if(!choices.includes(form.category))setForm(x=>({...x,category:choices[0]}))},[form.type]); const submit=e=>{e.preventDefault();onSave({...form});}; return <Modal title={entry?'Edit transaction':'Add transaction'} onClose={onClose}><form onSubmit={submit}><div className="toggle">{['expense','income'].map(type=><button type="button" className={form.type===type?'selected':''} onClick={()=>setForm({...form,type})} key={type}>{type}</button>)}</div><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Note<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="two"><label>Amount<input required type="number" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{choices.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Date<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label><label>Repeat<select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}><option value="once">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="biweekly">Bi-weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label>{form.recurrence!=='once'&&<label>Ends on<input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label>}<button className="primary" type="submit">Save transaction</button></form></Modal> }
function BudgetModal({budget,onClose,onSave}) { const [value,setValue]=useState(budget);return <Modal title="Set monthly budget" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(value)}}><label>Monthly spending budget<input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)}/></label><button className="primary">Save budget</button></form></Modal> }
const Modal=({title,onClose,children})=><div className="backdrop"><section className="modal"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>;
function Auth({onDone}) { const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [signup,setSignup]=useState(false);const [message,setMessage]=useState('');const submit=async e=>{e.preventDefault();const r=signup?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error)setMessage(r.error.message);else if(signup)setMessage('Account created. Check your email, then sign in.');else onDone()};return <main className="auth"><form onSubmit={submit}><b className="logo">$</b><h1>{signup?'Create your account':'Sign in'}</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="8"/></label><p>{message}</p><button className="primary">{signup?'Create account':'Sign in'}</button><button type="button" className="link" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'Need an account? Sign up'}</button></form></main> }
function repeatDates(form) { if(form.recurrence==='once'||!form.end)return [form.transaction_date];const start=new Date(`${form.transaction_date}T00:00:00`),end=new Date(`${form.end}T00:00:00`),out=[];for(let i=0;i<500;i++){let d=new Date(start);if(form.recurrence==='daily')d.setDate(d.getDate()+i);else if(form.recurrence==='weekly')d.setDate(d.getDate()+i*7);else if(form.recurrence==='biweekly')d.setDate(d.getDate()+i*14);else d.setMonth(d.getMonth()+i*(form.recurrence==='quarterly'?3:form.recurrence==='yearly'?12:1));if(d>end)break;out.push(dateKey(d))}return out;}
createRoot(document.getElementById('root')).render(<App/>);
